#!/home/snehil/miniforge3/envs/data-work/bin/python

# plots fits files in usr/local/bin as pfits

import astropy.units as u
import sunpy.map
# import sunpy.data.sample
import matplotlib.pyplot as plt
import matplotlib.colors
import argparse
from glob import glob
# from astropy.coordinates import SkyCoord
from astropy.visualization import ImageNormalize, SqrtStretch

def plot(files):

    sequence = sunpy.map.Map(files, sequence=True)

    fig = plt.figure()
    ax = fig.add_subplot(projection=sequence.maps[0])
    # ani = sequence.plot(axes=ax, cmap="hmimag", norm=plt.Normalize(-1500, 1500))
    ani = sequence.plot(axes=ax, clip_interval=(1, 99.5)*u.percent) # clip & norm read
    if save:
        ani.save(f'./{args.plot}/animation/ani.mp4')
    plt.show()


if __name__=="__main__":
    parser = argparse.ArgumentParser()

    group = parser.add_mutually_exclusive_group()

    parser.add_argument('-p', "--path", nargs='?', default='./*.fits', const='./*.fits',
                        help="path to file") 
    args = parser.parse_args()
    
    files = glob(f"{args.path}")
    files.sort()
    map = sunpy.map.Map(files[0])

    fig, ax1 = plt.subplots(nrows=1, ncols=1, subplot_kw={'projection':map, })

    map.plot(axes=ax1, clip_interval=(1, 99.5)*u.percent) # , norm=matplotlib.colors.LogNorm()

    # map.draw_contours([1,5,10,50,90]*u.percent)
    plt.colorbar() # need to fix how to have global colorbar and not only on the last
    plt.show()
